### ISSUE TITLE
服务器上挂机器人，本机是否打开不了网站

### ISSUE THREAD

**Issue by 70loKirin** [guoba-yunzai/guoba-plugin#1]
我使用的服务器只能局域网下ssh命令行连接，请问这样的话我是不是无论如何都打开不了网站

**Comment by sjlei** [comment]
使用 ssh 命令行连接的时候那个地址就可以访问，但是如果开了防护墙，记得要开放50831端口号。

**Comment by 70loKirin** [comment]
> 使用 ssh 命令行连接的时候那个地址就可以访问，但是如果开了防护墙，记得要开放50831端口号。

好的 谢谢
