### ISSUE TITLE
喵喵帮助背景透明度小建议（插件真的太方便啦）

### ISSUE THREAD

**Issue by DivinationHW** [guoba-yunzai/guoba-plugin#11]
![image](https://user-images.githubusercontent.com/107331343/190088807-9e988b5a-cc6d-41f2-b20d-1f5d50ba57c3.png)
这边调节了透明度，但锅巴插件中的喵喵帮助编辑显示不出来，如图：
![image](https://user-images.githubusercontent.com/107331343/190089027-a1e4eb61-5e6d-4726-99e2-96d944a69684.png)
![47da7298951e05f7d791622c896f43a0](https://user-images.githubusercontent.com/107331343/190089036-02d355ae-c558-43d2-841c-4da65a2b703c.jpg)
在未来是否会考虑加上透明度调节和字体颜色等调节功能呢？当然，即使没有，这个插件也是极强的。

**Comment by sjlei** [comment]
因为现在样式是写死的，不是动态读取的，所以会出现这种情况……
后面会考虑加一下透明度调节，不过最好还是等喵佬开放配置，不然很容易更新冲突。

**Comment by heny** [comment]
> ![image](https://user-images.githubusercontent.com/107331343/190088807-9e988b5a-cc6d-41f2-b20d-1f5d50ba57c3.png) 这边调节了透明度，但锅巴插件中的喵喵帮助编辑显示不出来，如图： ![image](https://user-images.githubusercontent.com/107331343/190089027-a1e4eb61-5e6d-4726-99e2-96d944a69684.png) ![47da7298951e05f7d791622c896f43a0](https://user-images.githubusercontent.com/107331343/190089036-02d355ae-c558-43d2-841c-4da65a2b703c.jpg) 在未来是否会考虑加上透明度调节和字体颜色等调节功能呢？当然，即使没有，这个插件也是极强的。

大佬你这小图标从哪来的呀，能否分享一下

**Comment by DivinationHW** [comment]
> > ![图像](https://user-images.githubusercontent.com/107331343/190088807-9e988b5a-cc6d-41f2-b20d-1f5d50ba57c3.png)这边调节了透明度，但锅巴插件中的喵喵帮助编辑显示不出来，如图： ![图像](https://user-images.githubusercontent.com/107331343/190089027-a1e4eb61-5e6d-4726-99e2-96d944a69684.png) ![47da7298951e05f7d791622c896f43a0](https://user-images.githubusercontent.com/107331343/190089036-02d355ae-c558-43d2-841c-4da65a2b703c.jpg) 在未来是否会考虑加上透明度调节和字体颜色等调节功能呢？当然，即使没有，这个插件也是极强的。
> 
> 大佬你这小图标从哪来的呀，能否分享一下

我这个是朝大佬要的，很抱歉我没有权力分享别人的劳动成果，是官群小萌新大佬做的

**Comment by sjlei** [comment]
https://github.com/guoba-yunzai/guoba-plugin/commit/f396ece97678fd64658d2ed28d88ae01610ae265
新版编辑喵喵帮助的换肤功能，包括透明度设置等，均已兼容，更新即可。
