### ISSUE TITLE
docker环境下编辑喵喵帮助修改报错，cross-device link not permitted

### ISSUE THREAD

**Issue by 1294266616** [guoba-yunzai/guoba-plugin#13]
![image](https://user-images.githubusercontent.com/52421598/190209018-97b89280-edf4-4137-b755-d13c9d2513ce.png)
![image](https://user-images.githubusercontent.com/52421598/190209573-8aa88b34-99da-4884-b523-f85c01b084f6.png)

docker上运行云崽

**Comment by sjlei** [comment]
没有在docker上安装过云崽，暂时无法复现，后面我有空了安装一下。
不过感觉这个报错很奇怪，提示不允许跨设备连接，没有想明白是什么场景下会出现这种问题。

**Comment by 1294266616** [comment]
> 没有在docker上安装过云崽，暂时无法复现，后面我有空了安装一下。 不过感觉这个报错很奇怪，提示不允许跨设备连接，没有想明白是什么场景下会出现这种问题。

今天修改下还是报错但帮助的修改能正常保存

**Comment by sjlei** [comment]
这个问题应该是改好了，你更新下试试

**Comment by 1294266616** [comment]
> 这个问题应该是改好了，你更新下试试
好了没有显示错误了
