### ISSUE TITLE
锅巴插件配置页面无法配置多个主人

### ISSUE THREAD

**Issue by jun1stu** [guoba-yunzai/guoba-plugin#16]
使用锅巴插件的配置页面我发配置多个主人，选择第二个人的时候，默认替换掉第一个，以此类推，望修复

**Comment by sjlei** [comment]
未复现该问题，截图看一下你的 other.yaml 配置文件，看看写法是否和示例保持一致。

![image](https://user-images.githubusercontent.com/34293221/190892788-1a81de3b-b7ab-48d5-9dc1-011051f275cd.png)
![image](https://user-images.githubusercontent.com/34293221/190892820-ae1d3df7-6dba-4830-9a3f-31067955ff00.png)

**Comment by jun1stu** [comment]
谢谢，发现与实例确实有个空格的区别，现在功能是正常的，非常感谢
