### ISSUE TITLE
浅提交一个问题，不知道是不是我操作有误

### ISSUE THREAD

**Issue by Zmincrix** [guoba-yunzai/guoba-plugin#17]
![image](https://user-images.githubusercontent.com/35093819/191164306-f18fcec1-af5b-48b3-944b-8c8401ba0634.png)

**Comment by sjlei** [comment]
是不是自己改过背景图片？估计是图片太大了吧

**Comment by sjlei** [comment]
优化已提交，请更新。
https://github.com/guoba-yunzai/guoba-plugin/commit/cb711999408197dadc9c2ec6e3f0d817c2fbf034
