### ISSUE TITLE
修改城市天气

### ISSUE THREAD

**Issue by BeterKing** [guoba-yunzai/guoba-plugin#2]
![ZB~DG1J(~PG3{AXH}2YJ0M2](https://user-images.githubusercontent.com/109637330/188318211-f57cb92b-0ec1-42f0-b40d-4861c87f14a2.png)
修改城市出现这种的话，界面就显示不出来了
![5R}N0GO5Q6$9K2ZH99TCWBJ](https://user-images.githubusercontent.com/109637330/188318244-e16f16ca-f42e-475c-8711-840ba94b43b8.png)

**Comment by sjlei** [comment]
啊这，居然会这样，等我改一下

**Comment by sjlei** [comment]
问题已修复，更新下即可
