### ISSUE TITLE
xiaofei-plugin 格式问题解析失败

### ISSUE THREAD

**Issue by 976863929** [guoba-yunzai/guoba-plugin#22]
![image](https://user-images.githubusercontent.com/44665525/192664678-e7a14db2-0e44-454f-9410-109455466de0.png)

**Comment by sjlei** [comment]
他多写了一个斜杠，先记一下，后续兼容

![image](https://user-images.githubusercontent.com/34293221/192667939-5a65d088-67f6-4fb9-8a8c-2d907665cd6f.png)
