### ISSUE TITLE
插件管理页面无法读取插件

### ISSUE THREAD

**Issue by tian564159391** [guoba-yunzai/guoba-plugin#24]
![image](https://user-images.githubusercontent.com/37993579/192801848-c7edc813-6462-453e-8805-0158c0e5b147.png)
喵喵帮助页面也无限宝错
![image](https://user-images.githubusercontent.com/37993579/192801885-79215477-1e9d-4c8a-82a2-31d2f9372b95.png)

**Comment by sjlei** [comment]
是gitee上的插件库（[Yunzai-Bot-plugins-index](https://gitee.com/yhArcadia/Yunzai-Bot-plugins-index)）被禁了，现在已经申诉回来了，应该是没问题了，如果还有问题就等半小时或者12小时后再试试（因为有缓存）
