### ISSUE TITLE
安装启动报错

### ISSUE THREAD

**Issue by Omoinemie** [guoba-yunzai/guoba-plugin#25]
![image](https://user-images.githubusercontent.com/31991443/192803024-7eefd1b8-af90-4a4d-a9c7-39614bce725a.png)
![image](https://user-images.githubusercontent.com/31991443/192803070-44ff296d-75f9-4d85-adc1-cadcce83fa03.png)

**Comment by sjlei** [comment]
详情见此issue
https://github.com/guoba-yunzai/guoba-plugin/issues/24#issuecomment-1261037848
