### ISSUE TITLE
使用pnpm安装依赖后启动云崽报错

### ISSUE THREAD

**Issue by bling-yshs** [guoba-yunzai/guoba-plugin#26]
![Snipaste_2022-10-02_18-49-29](https://user-images.githubusercontent.com/41812674/193450301-8aa246d3-ea31-4871-ab21-394fb5fbbdb4.png)

我先`git clone --depth=1 https://gitee.com/guoba-yunzai/guoba-plugin.git ./plugins/Guoba-Plugin/`

再`pnpm install --no-lockfile --filter=guoba-plugin`

应该没做错吧;w;..

云崽commit版本：https://github.com/Le-niao/Yunzai-Bot/commit/67981c8a5b734ea52dae6738b447e5da543f5a71

**Comment by bling-yshs** [comment]
我很确认安装锅巴之前没有安装别的其它的插件，并且云崽是可以正常启动的，并且且安装锅巴之前云崽已经关闭

**Comment by bling-yshs** [comment]
删掉--no-lockfile 用`pnpm install --filter=guoba-plugin`就能正常安装依赖..就很怪

**Comment by sjlei** [comment]
没有遇到过这个问题，你当时安装云崽的时候用的是pnpm吗？如果不是就不能通过pnpm安装锅巴的依赖。

**Comment by bling-yshs** [comment]
> 没有遇到过这个问题，你当时安装云崽的时候用的是pnpm吗？如果不是就不能通过pnpm安装锅巴的依赖。

我安装云崽是用的pnpm的诶;w;

**Comment by sjlei** [comment]
> 我安装云崽是用的pnpm的诶;w;

那我就不知道什么情况了，你这个问题是其他的依赖都丢失了，可以先删掉`node_modules`文件夹，然后再执行`pnpm install`，执行完之后不用单独安装锅巴的依赖，直接运行即可。

**Comment by bling-yshs** [comment]
> 那我就不知道什么情况了，你这个问题是其他的依赖都丢失了，可以先删掉`node_modules`文件夹，然后再执行`pnpm install`，执行完之后不用单独安装锅巴的依赖，直接运行即可。

会弹出一个不知名的窗口...搜一下没搜到QAQ
![01](https://user-images.githubusercontent.com/41812674/193452347-d0688635-d456-4c7f-ab98-92815e8ac7ac.png)

**Comment by bling-yshs** [comment]
> 那我就不知道什么情况了，你这个问题是其他的依赖都丢失了，可以先删掉`node_modules`文件夹，然后再执行`pnpm install`，执行完之后不用单独安装锅巴的依赖，直接运行即可。

瞎折腾一下成功了，先`git clone --depth=1 https://gitee.com/guoba-yunzai/guoba-plugin.git ./plugins/Guoba-Plugin/` 然后 `pnpm install` 然后会报enka-api的错误，再`pnpm add -w git+https://gitee.com/cv-hunag/enka-network-api.git` ，最后再`pnpm install`一次就行了

但我觉得用`pnpm install --no-lockfile --filter=guoba-plugin` 没法安装，这应该还是一个issue

**Comment by sjlei** [comment]
果然还是enka-api的问题，他这个经常安装不上，因为不是发布到npm上的，而是用的github仓库，导致很多人安装不上（网络原因）

> 但我觉得用`pnpm install --no-lockfile --filter=guoba-plugin` 没法安装，这应该还是一个issue

这个我测试了，全新clone一个云崽，然后先pnpm安装依赖，确保能正常使用，然后再clone锅巴插件，再`pnpm install --no-lockfile --filter=guoba-plugin`安装完之后没有任何问题。

**Comment by bling-yshs** [comment]
> 这个我测试了，全新clone一个云崽，然后先pnpm安装依赖，确保能正常使用，然后再clone锅巴插件，再`pnpm install --no-lockfile --filter=guoba-plugin`安装完之后没有任何问题。

你用全新的电脑就不是这个结果了，你之前安装过的话会有缓存，所以可以正常安装

**Comment by sjlei** [comment]
> 你用全新的电脑就不是这个结果了，你之前安装过的话会有缓存，所以可以正常安装

pnpm的缓存可以删，我删掉之后再测试结果还是一样，因为我连接github较为稳定，不会出现enka-api安装失败的情况。
总的来说还是enka-api使用了非npm仓库安装的问题，导致的很多人因为网络问题导致安装不上，我看已经有人给他提ISSUE了（https://github.com/yuko1101/enka-network-api/issues/1），希望能尽快发布到npm上吧。

----------
![image](https://user-images.githubusercontent.com/34293221/193514575-584fd3ba-aec6-48f8-b0d1-d2800bf1d65e.png)
![image](https://user-images.githubusercontent.com/34293221/193514524-111377ec-2378-43f6-8ce2-371977ec2251.png)

**Comment by bling-yshs** [comment]
> > 你用全新的电脑就不是这个结果了，你之前安装过的话会有缓存，所以可以正常安装
> 
> pnpm的缓存可以删，我删掉之后再测试结果还是一样，因为我连接github较为稳定，不会出现enka-api安装失败的情况。 总的来说还是enka-api使用了非npm仓库安装的问题，导致的很多人因为网络问题导致安装不上，我看已经有人给他提ISSUE了（ [yuko1101/enka-network-api#1](https://github.com/yuko1101/enka-network-api/issues/1) ），希望能尽快发布到npm上吧。
> 
> ![image](https://user-images.githubusercontent.com/34293221/193514575-584fd3ba-aec6-48f8-b0d1-d2800bf1d65e.png) ![image](https://user-images.githubusercontent.com/34293221/193514524-111377ec-2378-43f6-8ce2-371977ec2251.png)

啊okok，那我关issue了
