### ISSUE TITLE
安装插件遇到的问题

### ISSUE THREAD

**Issue by dh924** [guoba-yunzai/guoba-plugin#29]
![image](https://user-images.githubusercontent.com/38186417/195017807-b290ccb3-13e1-4e2f-ba40-bc4aaa1d2f22.png)
装这个插件的时候遇到这个问题，说当前配置不支持修改pnpm-lock.yaml文件 不知道怎么弄了 求解答。。。 系统是centos7

**Comment by sjlei** [comment]
命令里去掉`--no-lockfile`试一下

**Comment by dh924** [comment]
enen 安装成功了
