### ISSUE TITLE
用pnpm安装image-size和multer时有冲突

### ISSUE THREAD

**Issue by jiut** [guoba-yunzai/guoba-plugin#31]
安装完一个，另一个就显示未安装。

**Comment by sjlei** [comment]
锅巴的依赖是按照`README.md`里的方式安装的吗？
![image](https://user-images.githubusercontent.com/34293221/196082421-beaa8346-1d4c-40f8-8ad6-f39795a6ba8b.png)

**Comment by jiut** [comment]
是，但是后来要安装其他插件，又有冲突，就直接删掉了node modules，然后pnpm install。

**Comment by jiut** [comment]
之前按照文档里的步骤可以正常运作，但还是会显示image-size不存在，不过不影响运行。

**Comment by sjlei** [comment]
`image-size`是其他插件里的依赖，没有定义在package.json里所以会被pnpm删除，可以先使用`pnpm install --filter=guoba-plugin`安装完锅巴以后再安装其他的依赖一般来说就好了。

**Comment by jiut** [comment]
这里提到的报错都是开始运行机器人时显示的。

**Comment by jiut** [comment]
但是标题里的错误是在使用pnpm add image-size -w和pnpm add multer -w时产生的，安装完一个另一个就报错，无限循环。

**Comment by sjlei** [comment]
不需要单独`pnpm add multer -w`，执行了`pnpm install --filter=guoba-plugin`之后会自动安装上

**Comment by sjlei** [comment]
`pnpm add image-size -w`先执行或者后执行都试一遍，pnpm的这个机制比较坑

**Comment by jiut** [comment]
解决
