### ISSUE TITLE
后台功能未能实际更改相应配置文件

### ISSUE THREAD

**Issue by Birty112** [guoba-yunzai/guoba-plugin#32]
使用用户ck与开启自动签到功能未能改变相应的配置文件（Yunzai-Bot/plugins/genshin/defSet/mys内的set.yaml）需要用户手动更改配置文件才能实现相应功能   环境：华为云服务器 centOS7.6

**Comment by sjlei** [comment]
功能上经测试没有问题。修改的是`Yunzai-Bot/plugins/genshin/config/mys.set.yaml`文件，不应该修改defSet下的配置文件，因为那是默认配置，修改了可能会造成更新冲突，如果动态修改这两个选项没有生效，属于是Yunzai本体的bug，可以去Yunzai本体项目上提issue。
