### ISSUE TITLE
首次安装Guoba，sendToMaster 运行报错

### ISSUE THREAD

**Issue by lumineyuri** [guoba-yunzai/guoba-plugin#36]
环境 Ubuntu 20.04 LTS
nodejs 版本 16.17
`[YzBot][09:22:14.914][ERRO] TypeError: Cannot read properties of undefined (reading '0')
    at sendToMaster (file:///root/Yunzai-Bot/plugins/Guoba-Plugin/utils/common.js:123:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by sjlei** [comment]
没有设置主人QQ吗？

**Comment by sjlei** [comment]
看看`other.yaml`配置文件

**Comment by lumineyuri** [comment]
> 没有设置主人QQ吗？

![图片](https://user-images.githubusercontent.com/110418934/199916943-91d995d6-99cb-4367-9bd9-b147efe26a25.png)
设置了的

**Comment by sjlei** [comment]
那我周末测试一下

**Comment by ws147** [comment]
出现同样的问题

**Comment by leihongyang** [comment]
/**
 * 给主人发送消息
 * @param msg 消息内容
 * @param all 是否发送给所有主人，默认false
 * @param idx 不发送给所有主人时，指定发送给第几个主人，默认发送给第一个主人
 */
export async function sendToMaster(msg, all = false, idx = 0) {
  let masterQQ = await getMasterQQ()
  await replyPrivate(masterQQ, msg)
}

修改为这样即可

**Comment by sjlei** [comment]
问题已修复，更新即可。是我粗心大意了，这个问题只有第一次安装的时候才会出现
