### ISSUE TITLE
修改喵喵帮助具体是修改了哪几个文件

### ISSUE THREAD

**Issue by CICILC** [guoba-yunzai/guoba-plugin#37]
除了config/help.之外还有什么文件包含喵喵帮助的内容

**Comment by sjlei** [comment]
默认只会修改`miao-plugin/config/help.js`这个文件。

如果使用了修改图标功能，则会修改`miao-plugin/resources/help/icon.png`。

如果使用了皮肤功能，则会在`miao-plugin/resources/help/theme`目录下新建或修改皮肤。不会修改`default`皮肤。

如果存在老配置，并且不存在`miao-plugin/config/help.js`这个文件，则会读取老配置，并转换成新配置。

> 老配置文件包含：
> `miao-plugin/resources/help/help-cfg.js`
> `miao-plugin/resources/help/help-list.js`

**Comment by CICILC** [comment]
感谢
