### ISSUE TITLE
锅巴登录出现“请以主人的身份，向你的机器人发送#锅巴登录指令”

### ISSUE THREAD

**Issue by 370752206** [guoba-yunzai/guoba-plugin#38]
![锅巴登录的问题](https://user-images.githubusercontent.com/114566255/202887190-b3cffb74-162e-418c-a23b-47ffda08d309.jpg)
是以主人的身份发送的，但是打开链接后会这样提示

**Comment by sjlei** [comment]
是点击的机器人发送给你的链接吗？必须要在3分钟之内点击，如果要更换浏览器或者24小时以后，需要再次发送`#锅巴登录`

**Comment by 370752206** [comment]
> 是点击的机器人发送给你的链接吗？必须要在3分钟之内点击，如果要更换浏览器或者24小时以后，需要再次发送`#锅巴登录`

是用的机器人发的链接，用其他浏览器打开的那个链接，没有超过三分钟，当时复制当时就打开的，然后就出现上面那种情况，换了几个浏览器都是这样，直接打开链接的话又打不开，所以想问问怎么解决这问题0.0

**Comment by sjlei** [comment]
> 直接打开链接的话又打不开，所以想问问怎么解决这问题0.0

直接打开链接又打不开？什么意思，我看你这个图片里面不是打开了吗？
出现图片里的这种情况只能是机器人发给你的链接过期，或者是你没有复制完整，必须要一次不差的复制完整才行。

**Comment by 370752206** [comment]
> > 直接打开链接的话又打不开，所以想问问怎么解决这问题0.0
> 
> 直接打开链接又打不开？什么意思，我看你这个图片里面不是打开了吗？ 出现图片里的这种情况只能是机器人发给你的链接过期，或者是你没有复制完整，必须要一字不差的复制完整才行。

打不开可能是因为自带的浏览器不支持吧，直接点开链接的话就一直加载出不来网页，试了好几次都是一样，然后我就重新发送了一遍#锅巴登录，复制了网址后用其他浏览器打开就提示“请用主人的身份”图3是用的Via浏览器打开的，是一字没差复制的，愁死了
![1](https://user-images.githubusercontent.com/114566255/203212056-80468154-5725-4378-9255-281b555343ee.jpg)
![2](https://user-images.githubusercontent.com/114566255/203212073-52a5e871-fde3-4d55-aa3c-2940ebca0e48.jpg)
![3](https://user-images.githubusercontent.com/114566255/203212082-fb2cbbd2-0a92-488d-b65d-37003a4eeee1.jpg)
![4](https://user-images.githubusercontent.com/114566255/203212087-42b41a77-fe1f-4e5b-a6fb-2b05a25e16ea.jpg)

**Comment by 370752206** [comment]
> > 直接打开链接的话又打不开，所以想问问怎么解决这问题0.0
> 
> 直接打开链接又打不开？什么意思，我看你这个图片里面不是打开了吗？ 出现图片里的这种情况只能是机器人发给你的链接过期，或者是你没有复制完整，必须要一字不差的复制完整才行。

打不开可能是因为自带的浏览器不支持吧，直接点开链接的话就一直加载出不来网页，试了好几次都是一样，然后我就重新发送了一遍#锅巴登录，复制了网址后用其他浏览器打开就提示“请用主人的身份”图3是用的Via浏览器打开的，是一字没差复制的，愁死了
![1](https://user-images.githubusercontent.com/114566255/203212056-80468154-5725-4378-9255-281b555343ee.jpg)
![2](https://user-images.githubusercontent.com/114566255/203212073-52a5e871-fde3-4d55-aa3c-2940ebca0e48.jpg)
![3](https://user-images.githubusercontent.com/114566255/203212082-fb2cbbd2-0a92-488d-b65d-37003a4eeee1.jpg)
![4](https://user-images.githubusercontent.com/114566255/203212087-42b41a77-fe1f-4e5b-a6fb-2b05a25e16ea.jpg)

**Comment by sjlei** [comment]
一直转圈那的确可能是QQ内置浏览器版本过低导致的。
复制需要复制这一整段，要包括 /#/ 后的所有内容
![image](https://user-images.githubusercontent.com/34293221/203235255-2a9e9fcb-cc29-4b38-8a4b-ac4cfc131b2a.png)

**Comment by 370752206** [comment]
> 一直转圈那的确可能是QQ内置浏览器版本过低导致的。 复制需要复制这一整段，要包括 /#/ 后的所有内容 ![image](https://user-images.githubusercontent.com/34293221/203235255-2a9e9fcb-cc29-4b38-8a4b-ac4cfc131b2a.png)

复制是复制完了的，还是不知道是什么问题，我用电脑打开那个网址又可以打开，在手机上怎么也打不开，就很神奇
