### ISSUE TITLE
在CentOS系统环境下，无法访问网页

### ISSUE THREAD

**Issue by chen8665272** [guoba-yunzai/guoba-plugin#39]
![QQ图片20221123192502](https://user-images.githubusercontent.com/60909156/203535255-dcc1ff45-01d9-4413-a750-6b113b43f114.png)
本地环境，云崽无报错。换成Ubuntu和Debian环境下正常访问，是需要什么依赖吗？

**Comment by sjlei** [comment]
无报错就说明正常运行起来了，访问不了多半是因为防火墙（centos自带防火墙）

**Comment by sjlei** [comment]
https://gitee.com/guoba-yunzai/guoba-plugin/issues/I60SHC#note_14346059_link

**Comment by chen8665272** [comment]
谢谢大佬，已解决
