### ISSUE TITLE
后台接口路由问题

### ISSUE THREAD

**Issue by programerluffy** [guoba-yunzai/guoba-plugin#40]
不想直接暴露端口，想通过nginx反代一下，但是好像没有一个base路由

**Comment by sjlei** [comment]
绑定一个域名，然后直接代理根路径就行了

![image](https://user-images.githubusercontent.com/34293221/205272957-5c3ff8c9-3d11-48cc-b804-cea2271ebbde.png)

然后锅巴设置里面，自定义地址填上绑定的域名，关掉拼接端口号即可。
![image](https://user-images.githubusercontent.com/34293221/205272760-5d3be1d9-6cca-46a8-8c6c-256950ce8a8b.png)

测试一下
![image](https://user-images.githubusercontent.com/34293221/205273206-f34decfe-08d7-4fb5-9991-eadc3715d29c.png)
![image](https://user-images.githubusercontent.com/34293221/205273282-130ca2ad-47af-47cc-815e-23f604c26d02.png)

**Comment by sjlei** [comment]
绑定一个域名，然后直接代理根路径就行了

![image](https://user-images.githubusercontent.com/34293221/205273969-dacfb6c6-3b9e-433c-8cd8-4e329542683d.png)

然后锅巴设置里面，自定义地址填上绑定的域名，关掉拼接端口号即可。
![image](https://user-images.githubusercontent.com/34293221/205272760-5d3be1d9-6cca-46a8-8c6c-256950ce8a8b.png)

测试一下
![image](https://user-images.githubusercontent.com/34293221/205273206-f34decfe-08d7-4fb5-9991-eadc3715d29c.png)
![image](https://user-images.githubusercontent.com/34293221/205273282-130ca2ad-47af-47cc-815e-23f604c26d02.png)

**Comment by programerluffy** [comment]
是这样的，我的机子上跑了挺多奇奇怪怪的东西。

**Comment by programerluffy** [comment]
是这样的，我的机子上跑了一些奇奇怪怪的东西。我一般是将**/XXX**的请求代理到**:xxxx**端口，根路径代理我给了我自己跑的一份应用，但是Guoba好像并没有一个公共的路由地址（e.g:/Guoba）,去支持我这么做

**Comment by sjlei** [comment]
如果你有备案的域名的话，那倒好办了，只需要加一个子域名解析即可，比如`http://guoba.xxx.com`。
但是如果没有，只想通过ip访问，并解析到子目录下，比如`htttp://1.1.1.1/guoba`，这种确实暂时不支持，不过我会单独开一个ISSUE来跟进此功能，后面有时间会加上配置。
