### ISSUE TITLE
请问a13是没有适配吗

### ISSUE THREAD

**Issue by baizhili0** [guoba-yunzai/guoba-plugin#44]
在a13上运行云崽，锅巴插件启动报错![Screenshot_2023-02-10-14-28-25-929_com.termux.jpg](https://user-images.githubusercontent.com/112179934/218233411-5abc4b3f-e8fe-4bc1-8a2a-8a54e247e1be.jpg)

**Comment by sjlei** [comment]
现已由时雨的星空佬修复了，更新即可
