### ISSUE TITLE
加载错误，无法开启网页

### ISSUE THREAD

**Issue by wuweidmw** [guoba-yunzai/guoba-plugin#5]
![S WDZHO(8TX{ X%~1N~T%)X](https://user-images.githubusercontent.com/104341076/188945055-66b9dc2b-4edd-4af5-9ad5-cfbb4d87f6f5.png)
![C@~ INA0)U@1YW7E)(AMT~R](https://user-images.githubusercontent.com/104341076/188945054-f1000758-5874-4e91-af61-224f3a94b1eb.png)

**Comment by sjlei** [comment]
安装依赖
如果你是使用pnpm安装的云崽，那就只需要在云崽根目录执行下pnpm install即可

如果你是用普通的npm或者cnpm，那就需要安装以下依赖：

npm install body-parser
npm install jsonwebtoken
