### ISSUE TITLE
建议新增添加备案号的功能

### ISSUE THREAD

**Issue by GuiltyKirito** [guoba-yunzai/guoba-plugin#53]
因近期网安部门发邮件要求我的页面添加要在底部添加备案信息，但是考虑到我修改了页面后，如果拉取最新代码会被冲掉，所以请问能否新增一个可以配置备案号的地方？感谢

**Comment by sjlei** [comment]
配置已添加，更新即可
![image](https://github.com/guoba-yunzai/guoba-plugin/assets/34293221/945a7ab6-d22d-48a0-ac07-11c8bc78fe88)

**Comment by sjlei** [comment]
保存后刷新页面，在这里查看：

登录后
![image](https://github.com/guoba-yunzai/guoba-plugin/assets/34293221/0bd0951a-e12c-4de7-93ac-b52aa2ea54b3)

登录页面
![image](https://github.com/guoba-yunzai/guoba-plugin/assets/34293221/3623b19d-d284-4c96-992e-95f1aaddafd5)
