### ISSUE TITLE
[需求]烦请在这个备案号的位置加一个跳转连接的操作 感谢 

### ISSUE THREAD

**Issue by GuiltyKirito** [guoba-yunzai/guoba-plugin#55]
谢谢大佬，烦请在这个备案号的位置加一个跳转连接的操作 感谢 

外链地址：https://beian.miit.gov.cn/

![image](https://github.com/guoba-yunzai/guoba-plugin/assets/13746290/722183d0-0b07-4998-abd9-a8c423dee135)

![image](https://github.com/guoba-yunzai/guoba-plugin/assets/13746290/3fb67984-d49f-4377-84d8-415615ca915e)

**Comment by sjlei** [comment]
加上了
