### ISSUE TITLE
guoba.support.js能否支持格式检查？

### ISSUE THREAD

**Issue by CUZNIL** [guoba-yunzai/guoba-plugin#56]
具体来讲，就是输入配置以后点保存或者是输完就会提示格式不符然后停止保存。

比如：

![image](https://github.com/guoba-yunzai/guoba-plugin/assets/76582404/97915c95-15a5-49b7-bdd2-6b49c46a2c98)

希望能在点击红框输入内容后能在格式不正确时提示不符合目标格式然后阻止保存。

我试了下HTML <input> pattern，但是似乎不是用的这个，改了没效果，所以实在不清楚该怎么操作就来问了

**Comment by sjlei** [comment]
可以使用正则匹配，参考下面的写法：

```js
        {
          label: '联系方式',
          field: 'telphone',
          component: 'Input',
          rules: [
            // 正则匹配
            {pattern: /^1[3456789]\d{9}$/, message: '手机号码格式有误'}
          ],
        },
        {
          field: 'group',
          label: '群号',
          component: 'Input',
          componentProps: {
            placeholder: '请输入群号',
          },
          rules: [
            {required: true, message: '群号得填上才行哦~'},
            // 正则匹配
            {pattern: '^\\d+$', message: '群号应该是纯数字的吧'},
            {min: 5, message: '真的有这么短的群号吗？'},
            {max: 10, message: '太…太长了……'},
          ],
        },
```

**Comment by CUZNIL** [comment]
> 可以使用正则匹配，参考下面的写法：
> 
> ```js
>         {
>           label: '联系方式',
>           field: 'telphone',
>           component: 'Input',
>           rules: [
>             // 正则匹配
>             {pattern: /^1[3456789]\d{9}$/, message: '手机号码格式有误'}
>           ],
>         },
>         {
>           field: 'group',
>           label: '群号',
>           component: 'Input',
>           componentProps: {
>             placeholder: '请输入群号',
>           },
>           rules: [
>             {required: true, message: '群号得填上才行哦~'},
>             // 正则匹配
>             {pattern: '^\\d+$', message: '群号应该是纯数字的吧'},
>             {min: 5, message: '真的有这么短的群号吗？'},
>             {max: 10, message: '太…太长了……'},
>           ],
>         },
> ```

多谢！很有用

![image](https://github.com/guoba-yunzai/guoba-plugin/assets/76582404/317bb662-90eb-4975-ac0f-8cde548dc015)
