### ISSUE TITLE
白名单群选择器只会保存当前页

### ISSUE THREAD

**Issue by Tsuk1ko** [guoba-yunzai/guoba-plugin#57]
[看到 gitee 有相同 issue](https://gitee.com/guoba-yunzai/guoba-plugin/issues/I70RA2)，因为那边没有附件功能发视频比较麻烦故在此新开 issue

我也被相同问题困扰，下面是复现视频，为了保护隐私我将群头像、群号、群名用css隐藏了

以前我的临时解决方案是把每页个数设置到最大，50个还是100个，但今天发现好像改了，上限只有20个，没辙了

https://github.com/guoba-yunzai/guoba-plugin/assets/24877906/279cf36c-02f2-4d17-a375-3ca94f173a6f

![image](https://github.com/guoba-yunzai/guoba-plugin/assets/24877906/6fcf3a53-e59c-482d-bf1f-39e28eace091)

**Comment by sjlei** [comment]
问题复现了，找到原因了，如图所示。
![image](https://github.com/guoba-yunzai/guoba-plugin/assets/34293221/97e0350c-c98a-41d6-8c5f-2c972a32abf6)

周末修一下，暂时可以先点击行选中，而不点击复选框选中解决。
