### ISSUE TITLE
【Bug】other的设置

### ISSUE THREAD

**Issue by Dnyo666** [guoba-yunzai/guoba-plugin#63]
## 后台是这样的的，没有私聊通行符的设置
[
![image](https://github.com/guoba-yunzai/guoba-plugin/assets/73740313/c77dac86-d745-446b-9943-d08ab7821cbd)
](图片)
## 但是自行设置other.yaml后重启机器人，发现仍然能够私聊机器人（其他字符）
![image](https://github.com/guoba-yunzai/guoba-plugin/assets/73740313/88c1c0b1-df57-47e4-bffe-59381f83cf0c)
![image](https://github.com/guoba-yunzai/guoba-plugin/assets/73740313/be24be06-c1f0-4b84-a923-68169789721c)
## 不知道是锅巴的问题还是喵崽的问题，在此做一个反馈

**Comment by sjlei** [comment]
![image](https://github.com/guoba-yunzai/guoba-plugin/assets/34293221/59f80243-d743-4f82-9f66-0754f32f9581)
可能是这个 null 的问题，我有空了测试修复一下，你可以试试删掉之后好不好使
