### ISSUE TITLE
出现故障：Cannot read properties of undefined (reading 'iconPath')

### ISSUE THREAD

**Issue by ldcivan** [guoba-yunzai/guoba-plugin#66]
![微信截图_20240510232919](https://github.com/guoba-yunzai/guoba-plugin/assets/69411867/5742953b-e834-4bf8-a56a-eabbd8235141)
问题如图，miao yunzai本体无错误log输出

**Comment by Yukikaya** [comment]
我也是QAQ（把版本换回去好麻烦的样子...）

**Comment by sjlei** [comment]
目前没有复现，可能是安装的哪个插件写法不规范导致的，现在已经尽可能做了兼容判断，可以更新一下试试，但是可能还会有其他情况，能否把你安装的插件列一下，我去看看原因。

**Comment by ldcivan** [comment]
> 目前没有复现，可能是安装的哪个插件写法不规范导致的，现在已经尽可能做了兼容判断，可以更新一下试试，但是可能还会有其他情况，能否把你安装的插件列一下，我去看看原因。

问题是在添加以下plugin后出现的：

* liangshi-calc
* phi-plugin
* skland-plugin
* Yunzai-Kuro-Plugin

若需要全部plugin列表，可能要晚点给到您

**Comment by sjlei** [comment]
感谢，已确认问题是`phi-plugin`的写法问题，已做兼容，更新即可。如果还有其他问题欢迎再提issue

**Comment by ldcivan** [comment]
感谢 问题已解决
