### ISSUE TITLE
权限异常

### ISSUE THREAD

**Issue by MatchaDog** [guoba-yunzai/guoba-plugin#9]
用主人账号输入 `#锅巴帮助` 后，返回“暂无权限”
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/35016589/189790473-9daac011-2d53-4e40-bdbc-b2428a808b40.png">
<img width="374" alt="image" src="https://user-images.githubusercontent.com/35016589/189790495-ff7f1766-65d9-41a3-8e0f-deea94e56a0f.png">

**Comment by sjlei** [comment]
你的写法不对，这是云崽的问题，建议参考`blackQQ`的写法
